### ISSUE TITLE
Avoid creating objects for every second of video

### ISSUE THREAD

**Issue by jonreeve** [novoda/no-player#103]
#### Problem

Strong types are definitely a generally good thing, but in some cases not so appropriate. For VideoPosition we are creating one any time someone queries it. The heartbeat callback is used by many listeners who then query the position, every second. Creating these objects is definitely overkill and could even lead to heap fragmentation, etc. It's quite typical in video work to simply use a 'long seconds' for this kind of thing.

#### Potential Solution

Use a simple long for position.

Worth considering updating the heartbeat callback method signature to simply pass the position and duration (as longs) at this point, since every listener generally just asks for these two things. The player reference shouldn't really be needed, and if it really is needed then when the listener is created it probably could have been given that reference directly.

#### Impact

* Changes public API
* Avoids a lot of unnecessary object churn.

**Comment by ouchadam** [comment]
seems like this has been addressed  👍
