### ISSUE TITLE
Deprecate getListeners() in favour of add + remove methods

### ISSUE THREAD

**Issue by jonreeve** [novoda/no-player#104]
#### Problem

Having `player.getListeners().addMyListener(X)` rather than simply `player.addMyListener(X)` makes for a more complicated interface and more brittle tests. Also applies to remove methods.

#### Potential Solution

Add the latter method, and ultimately migrate away from the old one, but we could simply deprecate it for now.

#### Impact

Nice and safe if we just add these and deprecate the old ones. Really good for testing things that use noplayer as a collaborator though.

**Comment by ouchadam** [comment]
We originally had this and chose to avoid as the `NoPlayer` is an interface and meant adding wayyy too many methods to impls.

**Comment by Mecharyry** [comment]
@ouchadam -> https://github.com/novoda/no-player/pull/108

**Comment by ouchadam** [comment]
cc'ing @Dorvaryn and @fourlastor and they were part of the original discussions (if I remember correctly)

**Comment by Mecharyry** [comment]
Won't fix. Client applications can wrap the `listeners` providing a more accessible api if they wish.
