### ISSUE TITLE
Add support for TextureView

### ISSUE THREAD

**Issue by mr-archano** [novoda/no-player#149]
#### Problem

At the moment the integration of `ExoPlayer`/`MediaPlayer` is relying on the client to use a `SurfaceView` as host of the video buffer. This entails a rendering performance problem when the video is hosted in scrollable containers (eg: a `RecyclerView`), a known issue as described in the [official documentation from `ExoPlayer`](https://google.github.io/ExoPlayer/faqs.html#how-do-i-get-smooth-animationscrolling-of-video):
> `SurfaceView` rendering wasn’t properly synchronized with view animations until Android N. On earlier releases this could result in unwanted effects when a `SurfaceView` was placed into scrolling container, or when it was subjected to animation. Such effects included the `SurfaceView`’s contents appearing to lag slightly behind where it should be displayed, and the view turning black when subjected to animation.

#### Potential Solution

The `no-player` API is providing facades for both `ExoPlayer` and `MediaPlayer`, but one of the callbacks that clients have to provide makes use of [`android.view.SurfaceHolder`](https://developer.android.com/reference/android/view/SurfaceHolder), a component that is tightly coupled to the `SurfaceView` lifecycle.
Both media frameworks provide APIs that accept a [`Surface`](https://developer.android.com/reference/android/view/Surface) in lieu of `SurfaceHolder`, altho the support in `MediaPlayer` for those looks to be API 14+ (still below the minsdk of the library afaict).

It should be relatively easy to change the implementation of [`SurfaceHolderRequester.Callback`](https://github.com/novoda/no-player/blob/3307272f21a81919dc230aead3791a93809e330f/core/src/main/java/com/novoda/noplayer/SurfaceHolderRequester.java#L11-L15) to deprecate the use of `SurfaceHolder` and introduce a new callback accepting a plain `Surface` instead.

#### Impact

Promoting the use of `Surface` instead of `SurfaceHolder` will allow the consumers to choose `SurfaceView` or `TextureView` on their side without any repercussion on the player itself.
As suggested above we could try to go for duplication + deprecation as first step, but afaict clients will be affected by the change anyway, and adjusting to the new API is pretty trivial (using `SurfaceHolder.getSurface()` to retrieve the surface to pass to the callback.

**Comment by Mecharyry** [comment]
I'll start taking a look at this and track against https://github.com/novoda/no-player/tree/NO-149/surface_feature and https://github.com/novoda/no-player/tree/NO-149/surface

**Comment by Mecharyry** [comment]
I have a branch where I was working on this previously, I'll update and see how much work is remaining.

**Comment by ouchadam** [comment]
worth mentioning `SurfaceView` was a requirement for DRM content on mediaplayer, need to double check with exoplayer

**Comment by mr-archano** [comment]
Apparently just swapping the `SurfaceHolder` for a `Surface` (see #154) introduces some side effects, showing as black artifacts when using a `SurfaceView` to render the video.

Needs more investigation.

**Comment by ouchadam** [comment]
support readded with #160
