### ISSUE TITLE
Align portrait video to center-horizontal 

### ISSUE THREAD

**Issue by ayon115** [novoda/no-player#194]
I want to align the video to center horizontal within the playerView. Current portrait mode videos are shown Left aligned in my app. How can I do that ? 

Thanks for the help.

**Comment by Mecharyry** [comment]
Hi @ayon115, `PlayerView` is an interface from which you can implement your own portrait video view. Last I checked the demo uses portrait and is centre aligned. My guess is that you are using the incorrect `layout_width` or/and `layout_gravity` but I wouldn't know for sure without seeing your code or the UI.

**Comment by Mecharyry** [comment]
No response from issuer, closing.
