### ISSUE TITLE
support audio playback

### ISSUE THREAD

**Issue by ouchadam** [novoda/no-player#202]
#### Problem

Currently the library only exposes playback of Video content although `mediaplayer` and `exoplayer` fully support audio playback (the library can be tricked by passing mp3 as a H264 content type).

`noplayer` also enforces a surface to be attached which is not necessary for audio content, eg playing in the background.

#### Potential Solution

- To not enforce a surface to be attached for audio content.
- Reuse the exoplayer extractor source for a new Audio content type
- Make a generic `loadContent(uri, options)` or provide separate `loadVideo` & `loadAudio`

#### Impact

Will allow `noplayer` to be used for non video purposes.

**Comment by Mecharyry** [comment]
That's a good idea, would be interesting to support both 😄
