### ISSUE TITLE
NoPlayerView use generic views

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#34]
#### Problem
`NoPlayerView` relies on views that are exposed through the `ExoPlayer` package. If we were to ever drop support for `ExoPlayer` we would need to rework the `NoPlayerView` to remove the unsupported views.

#### Potential Solution
Implement our own versions of the `ExoPlayer` views that will have a longer life support.

#### Impact
We are not using code specific to one implementation in the other implementation which could be problematic when providing support to clients.

**Comment by ouchadam** [comment]
fixed by #56 and #31
