### ISSUE TITLE
AndroidMediaPlayerFacade VisibleForTesting

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#35]
#### Problem
`VisibleForTesting` is present in `AndroidMediaPlayerFacade`. It was added to facilitate testing but is a code smell.

#### Potential Solution
Remove `VisibleForTesting` and expose creation of `MediaPlayer` through a factory or other medium.

#### Impact
Child classes currently have access to `MediaPlayer` which we do not want to expose.

**Comment by juankysoriano** [comment]
Done in #38
