### ISSUE TITLE
Null checks on AndroidMediaPlayerFacadeListeners

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#36]
#### Problem
There are `null` checks on listeners present in the `AndroidMediaPlayerFacade`, most of these appear to be redundant because they are set by us, not the client, in the `AndroidMediaPlayerImpl`.

#### Potential Solution
Check which listeners have `null` checks, see where they are set and whether or not we can remove the check. If we can, remove the `null` check.

#### Impact
We will remove redundant code making the class smaller and easier to read.

**Comment by juankysoriano** [comment]
Done in #38
