### ISSUE TITLE
PlayerFactory use a Builder

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#53]
#### Problem
Lot's of "discussions" around the `PlayerFactory` when adding the `DOWNGRADE_SECURE_DECODER` because we passed a boolean all the way down instead of having two different method signatures.

#### Potential Solution
Use the `Builder` pattern, it's ideal when you want to customise something.

#### Impact
Extensible and we can provide easily visible defaults.

**Comment by Mecharyry** [comment]
Pass down `MediaCodecSelector` when doing this.

**Comment by ouchadam** [comment]
fixed by #57
