### ISSUE TITLE
NoPlayer views

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#77]
#### Problem
Currently `NoPlayerView` relies on `ExoPlayer` view groups coupling `NoPlayer` to `ExoPlayer`. See [layout](https://github.com/novoda/no-player/blob/master/core/src/main/res/layout/noplayer_view.xml) for more information.

#### Potential Solution
We should have `NoPlayer` implementations of any views that the layout relies on and not be dependent on any views from an underlying `Player`.

#### Impact
We won't be coupled to `ExoPlayer` if we ever drop support for it. We have complete knowledge of the views in our domain.

**Comment by ouchadam** [comment]
to clarify the action for this issue, to include the `AspectRatioFrameLayout` in our library?

**Comment by Mecharyry** [comment]
Yes,any view that is part of the `exo-player` package and does not belong to us.
