### ISSUE TITLE
Assert PlayerView is attached

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#78]
#### Problem
We have a number of calls that rely on calling methods on the `PlayerView`. When calling on the `Player`, another class that can be null, we assert and throw should this be null. 

#### Potential Solution
Check if `PlayerView` is null and throw informing clients that they must attach a `PlayerView` in order to interact with it.

#### Impact
Consistency in the codebase to how we handle `@Nullable`. More informative error messaging for a user should they forget to attach a `PlayerView` rather than a `NullPointer`.

**Comment by Kartik2016** [comment]
Is the issue still open ? If yes please assign it to me id like to work on it! Thanks.

**Comment by Mecharyry** [comment]
I have a feeling that this was achieved mostly in the newest update of the library, @ouchadam can you confirm?

**Comment by ouchadam** [comment]
We're only asserting when `loadVideo` is called in the future we would like the library to be able to handle playback without a `playerView` for example continuing video playback as audio only.

**Comment by Mecharyry** [comment]
We should drop this issue then. I'll open a new one for what we plan in the future. Thanks @ouchadam. Sorry @Kartik2016 for the misinformation on this issue.
