### ISSUE TITLE
Break down InfoListener

### ISSUE THREAD

**Issue by rock3r** [novoda/no-player#8]
#### Problem
`com.novoda.noplayer.exoplayer.InfoListener` which we inherited from Google's legacy is enormous.

#### Potential Solution
Breakdown the `com.novoda.noplayer.exoplayer.InfoListener` into multiple focused interfaces.

#### Impact
Each class that implements `InfoListener` needs to implement all methods from the interface or provide them through an abstract class resulting in `// no-ops` which is a code smell.

**Comment by Mecharyry** [comment]
This has been completed in #23 Exo-player two facade and forwarders. We decided to supply a generic interface of `onNewInfo` supplying the calling method name and parameters. This will be released as part of `ExoPlayer two support`.
