### ISSUE TITLE
Initialise HashMaps with given size

### ISSUE THREAD

**Issue by Mecharyry** [novoda/no-player#84]
#### Problem
As per @zegnus comment [here](https://github.com/novoda/no-player/pull/83#discussion_r132960962), our `HashMap`s in the `InfoForwarder`s are not initialised to any given size but use the default.

#### Potential Solution
Initialise our maps with the correct size.

#### Impact
Reduce memory footprint.

**Comment by Mecharyry** [comment]
The latest version of `HashMap` has this useful line of code:

```
else if (initialCapacity < DEFAULT_INITIAL_CAPACITY) {
            initialCapacity = DEFAULT_INITIAL_CAPACITY;
        }
```

Defeating the point of providing a smaller initial size for optimising this area of the code. 

An alternative solution would be to implement a list of items made of `KeyValuePairs` rather than using a map. This could also be a custom first class collection so that we can specify how the items are printed. Just a thought.

@zegnus do you have any preference? As you raised the issue in a comment 😄

**Comment by zegnus** [comment]
First class collection would be my preference ;)

**Comment by ouchadam** [comment]
we could also use `ArrayMap`
