### ISSUE TITLE
Player DRM interfaces are empty

### ISSUE THREAD

**Issue by rock3r** [novoda/no-player#9]
The `DrmHandler` and the `ClassicDrm` are empty due to the drm being acquired at an earlier stage, before the player is created, this is not case for modular drm which will need to be passed to the player.

The code needs to be reworked to make sense since the classic drm is no longer required to be triggered by the `Player`

_(Moved over from the project of origin)_

**Comment by ataulm** [comment]
This has been done - though we'll probably need to revisit - where we removed the ClassicDrmHandler (I guess before the creation of this repo since I can't see any reference to it).
